#### See what axis will do with arrays:

In [2]:
import numpy as np
arr=np.array([[1,2,3,4],[2,3,4,5],[5,6,74,2]])
arr

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 5,  6, 74,  2]])

In [3]:
#Now using axis to find the sum of elements in the array
#axis=0 represents the columns

In [4]:
arr.sum(axis=0)
#this code will give the sum of each column

array([ 8, 11, 81, 11])

In [5]:
#In 1D arrays the axis will be zero, passing axis=0 will give you error.
#Now axis=1 in a 2D array

In [7]:
arr.sum(axis=1)
#gives us the sum of each row

array([10, 14, 87])