In [1]:
#Finding the transpose of the array

In [2]:
import numpy as np
arr=np.array([[1,23,45],[21,5,3],[3,4,6]])
arr

array([[ 1, 23, 45],
       [21,  5,  3],
       [ 3,  4,  6]])

In [3]:
#syntax to find the transpose
arr.T

array([[ 1, 21,  3],
       [23,  5,  4],
       [45,  3,  6]])

In [4]:
#showing the array a 1D
arr.flat #creates 1D iterator

In [5]:
for item in arr.flat:
    print(item)
    type(item)

1
23
45
21
5
3
3
4
6


In [6]:
#finding the dimention of the array
arr.ndim

2

In [7]:
#finding size of the array
arr.size

9

In [8]:
#bytes used by the arrya
arr.nbytes

36

##### Max, min, sort:

In [9]:
#finding the index of minimum element of the array

In [17]:
arr.argmin()

0

In [18]:
#finding the index of min element of each row
arr.argmin(axis=0)

array([0, 2, 1], dtype=int64)

In [14]:
#index of the maximum element

In [15]:
arr.argmax()

2

In [19]:
#finding the index of maximum element of each row

In [21]:
arr.argmax(axis=1)

array([2, 0, 2], dtype=int64)

In [22]:
#sorting

In [31]:
arr.argsort()

array([[0, 1, 2],
       [2, 1, 0],
       [0, 1, 2]], dtype=int64)

##### Array addition, subtraction, multiplication:

In [34]:
arr1=np.arange(3,12).reshape(3,3)
arr2=np.arange(10,19).reshape(3,3)

In [ ]:
#adding arrays:

In [36]:
arr1+arr2

array([[13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [37]:
#substracting arrays:

In [39]:
arr1-arr2

array([[-7, -7, -7],
       [-7, -7, -7],
       [-7, -7, -7]])

In [40]:
#multiplication af arrays:

In [42]:
arr1*arr2

array([[ 30,  44,  60],
       [ 78,  98, 120],
       [144, 170, 198]])

In [43]:
# Finding the square root of the array elements

In [45]:
np.sqrt(arr)

array([[1.        , 4.79583152, 6.70820393],
       [4.58257569, 2.23606798, 1.73205081],
       [1.73205081, 2.        , 2.44948974]])

In [47]:
#sum of all elements in the array:

In [49]:
arr.sum()

111

In [50]:
#minimum value of the array:

In [52]:
arr.min()

1

In [54]:
#maximum value of the array:

In [56]:
arr.max()

45

In [57]:
#finding which all elements follows a particular condition:

In [59]:
np.where(arr>10)

(array([0, 0, 1], dtype=int64), array([1, 2, 0], dtype=int64))

In [60]:
#Counting the non-zero elements in an array:

In [62]:
np.count_nonzero(arr)

9

In [66]:
#gives the position tuple of non-zero elements
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [ ]:
#Visit: scipy.org

In [65]:
arr

array([[ 1, 23, 45],
       [21,  5,  3],
       [ 3,  4,  6]])