In [5]:

import pyforest

a=np.array([[1,2,34,5],[9,5,4,7]])
a[:]



<IPython.core.display.Javascript object>

array([[ 1,  2, 34,  5],
       [ 9,  5,  4,  7]])

In [3]:
active_imports()

import numpy as np


['import numpy as np']

In [42]:
np.full_like(a,random.randint(1,3))

<IPython.core.display.Javascript object>

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [1]:
lst=[1,2,3,4,5,6,7,8,9,10]
for i in range(10):
    lst[i]=np.random.randint(1,3)
lst

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[2, 1, 2, 1, 1, 2, 1, 2, 1, 1]

In [51]:
np.random.randint(10,size=(4,5))

<IPython.core.display.Javascript object>

array([[3, 2, 7, 7, 8],
       [5, 2, 8, 7, 0],
       [9, 6, 6, 3, 6],
       [2, 0, 3, 9, 1]])