### Reading text using Numpy:


In [11]:
import numpy as np
data=np.genfromtxt('test.txt',delimiter=',',dtype='int32')
data

array([[ 1, 12, 12, 21,  3,  4, 34,  6],
       [ 4,  2, 54, 46,  7,  8,  9, 56],
       [ 2, 45,  6,  2, 43,  6,  7,  4]])


###### Boolean Masking and advanced Indexing:

In [17]:
(data<=50)

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [24]:
data[data<=50]

array([ 1, 12, 12, 21,  3,  4, 34,  6,  4,  2, 46,  7,  8,  9,  2, 45,  6,
        2, 43,  6,  7,  4])

In [34]:
((data>50) & (data<100))

array([[False, False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False,  True],
       [False, False, False, False, False, False, False, False]])

In [41]:
arr=np.arange(1,31).reshape(6,5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [44]:
arr[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [47]:
arr[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [48]:
arr[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])